sudo: false

if: type = push

branches:
  only:
    - master
    - /^release\/.*/

matrix:
  include:
    # Linux
    - language: java
      os:
        - linux

      jdk:
        - openjdk11

      install: true

      script: ./gradlew

    # macOS
    - language: java
      os:
        - osx

      jdk:
        - openjdk11

      install: true

      script: ./gradlew

    # Windows
    #- language: shell
    #  os: windows
    #  before_install:
    #    - choco install adoptopenjdk11 --version 11.0.4.11
    #    - choco install zip
    #    - export PATH=$PATH:"/c/Program Files/AdoptOpenJDK/jdk-11.0.4+11/bin"
    #  script: ./gradlew
