sudo: false

if: type = push

branches:
  only:
    - master
    - /^release\/.*/

matrix:
  include:
    # Linux
    - language: java
      os:
        - linux

      jdk:
        - openjdk11

    # macOS
    - language: java
      os:
        - osx

      jdk:
        - openjdk11

    # Windows
    #- language: shell
    #  os: windows
    #  before_install:
    #    - choco install openjdk --version 11.0.1 --verbose
    #  script: ./gradlew check
